[package]
name = "backend"
version = "0.1.0"
authors = ["jonathan.pavlik"]

[dependencies]
toml = "*"
serde_derive = "*"
serde = "*"
regex = "*"
reqwest = "*"
rss = { version = "*", features = ["from_url"] }
chrono = "*"
scraper = "*"