[package]
name = "backend"
version = "0.1.0"
authors = ["jonathan.pavlik"]

[dependencies]
toml = "0.4.5"
serde_derive = "1.0.27"
serde = "1.0.27"
regex = "0.2.6"
reqwest = "0.8.5"
rss = { version = "1.0", features = ["from_url"] }
chrono = "0.4.0"
select = "*"