[[feed]]
  feed_url = "http://www.wuxiaworld.com/feed/chapters/desolate-era"
  feed_type = "file"
  tracker = "feeds/last_de"
  output_path = "books/de/"

  [[feed.task]]
    name = "read feed"
    feed = true


  [[feed.task]]
    name = "get chapter title and open chapter page"
    match_filename = "de-book-[^/]+"
    get = true
    open_url = true

  [[feed.task]]
    name = "chapter content to file format"
    selector = ".section-content p"
    selector_body = true
    output_concat = "\n"

  [[feed.task]]
    name = "write to file"
    write = true

# [[feed]]
#   feed_url = "http://www.wuxiaworld.com/category/de-chapter-release/feed/"
#   feed_type = "file"
#   tracker = "feeds/last_de"
#   output_path = "books/de/"

#   [[feed.task]]
#     name = "read feed"
#     task_type = "text"

#   [[feed.task]]
#     name = "open chapter homepage"
#     task_type = "dom"
#     open_url = true

#   [[feed.task]]
#     name = "find chapter urls"
#     task_type = "text"
#     selector = "div[itemprop=\"articleBody\"] p a"
#     selector_attr = "href"

#   [[feed.task]]
#     name = "filter out bad urls"
#     task_type = "text"
#     filter = "http://www\\.wuxiaworld\\.com/desolate-era-index/de-book-"

#   [[feed.task]]
#     name = "get filename and open chapter link"
#     task_type = "dom"
#     match_filename = "de-book-[^/]+" # takes input matches regex
#     open_url = true

#   [[feed.task]]
#     name = "get chapter content to file format"
#     task_type = "text"
#     selector = "div[itemprop=\"articleBody\"] p"
#     selector_body = true
#     output_concat = "\n"

#   [[feed.task]]
#     name = "write to file"
#     task_type = "file"

